// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC20IMSJV8nxenHgr1q2_8J2rbMJnX2ts',
    appId: '1:550846873923:web:6cbfbf9c3be12b7b28eff6',
    messagingSenderId: '550846873923',
    projectId: 'public-pulse-4b92c',
    authDomain: 'public-pulse-4b92c.firebaseapp.com',
    storageBucket: 'public-pulse-4b92c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc-D6JiE73znPEMW_j5CMniC9dcQNymSM',
    appId: '1:550846873923:android:b86bef4ba0f7e41928eff6',
    messagingSenderId: '550846873923',
    projectId: 'public-pulse-4b92c',
    storageBucket: 'public-pulse-4b92c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXxs0YS9HBjkoz-NygJMwyQRhq03a6geU',
    appId: '1:550846873923:ios:a524d5a0a464d1e728eff6',
    messagingSenderId: '550846873923',
    projectId: 'public-pulse-4b92c',
    storageBucket: 'public-pulse-4b92c.firebasestorage.app',
    iosClientId: '550846873923-khatvhoua9aorsldci5br2nq4m70fnch.apps.googleusercontent.com',
    iosBundleId: 'com.example.publicPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXxs0YS9HBjkoz-NygJMwyQRhq03a6geU',
    appId: '1:550846873923:ios:a524d5a0a464d1e728eff6',
    messagingSenderId: '550846873923',
    projectId: 'public-pulse-4b92c',
    storageBucket: 'public-pulse-4b92c.firebasestorage.app',
    iosClientId: '550846873923-khatvhoua9aorsldci5br2nq4m70fnch.apps.googleusercontent.com',
    iosBundleId: 'com.example.publicPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC20IMSJV8nxenHgr1q2_8J2rbMJnX2ts',
    appId: '1:550846873923:web:d8bb7cd17a9345db28eff6',
    messagingSenderId: '550846873923',
    projectId: 'public-pulse-4b92c',
    authDomain: 'public-pulse-4b92c.firebaseapp.com',
    storageBucket: 'public-pulse-4b92c.firebasestorage.app',
  );
}
